# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67458757efca4809f854b8cf221240349a1bc90a6350e6f5b8687763e851b2746db5a75ba3a697104bec18c05c8fd583717b1add156ba6e60a464ee99d536c9d

test:
  secret_key_base: bd741e3a8252fb824b3b358f9f28082c12261b62e81069b61d202a3204de27a05b7f5c321ea074c92fede0c35249a52d47f1f4e61cdedda3579e7f1c13e6f3ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
